vim.keymap.set("n", "<C-T>f", "<cmd>Telescope find_files<CR>")
vim.keymap.set("n", "<C-T>g", "<cmd>Telescope live_grep<CR>")
vim.keymap.set("n", "<C-T>G", "<cmd>Telescope grep_string default_text=<CR>")
vim.keymap.set("n", "<C-T>b", "<cmd>Telescope buffers<CR>")
vim.keymap.set("n", "<C-T>n", "<cmd>Telescope notify<CR>")
