vim.keymap.set("n", "<C-F>", "<cmd>Telescope find_files<CR>")
vim.keymap.set("n", "<C-G>", "<cmd>Telescope live_grep<CR>")
vim.keymap.set("n", "<C-T>g", "<cmd>Telescope grep_string default_text=<CR>")
vim.keymap.set("n", "<C-B>", "<cmd>Telescope buffers<CR>")
vim.keymap.set("n", "<C-T>n", "<cmd>Telescope notify<CR>")
