[tools]
air = "latest"
"aqua:8051Enthusiast/biodiff" = "latest"
"aqua:firecow/gitlab-ci-local" = "4.57.0"
"aqua:JanDeDobbeleer/oh-my-posh" = "latest"
"aqua:rhysd/vim-startuptime" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
"aqua:sharkdp/hexyl" = "latest"
"aqua:sheepla/pingu" = "latest"
awscli = "latest"
bat = "latest"
"cargo:pay-respects" = "latest"
delta = "latest"
dust = "1.1.1"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
golangci-lint = "latest"
go = "latest"
hyperfine = "1.19.0"
neovim = "latest"
nfpm = "latest"
node = "22.14.0"
"npm:aicommit2" = "latest"
"npm:czg" = "latest"
"npm:devcontainer" = "latest"
"npm:http-server" = "latest"
"npm:tabby-agent" = "latest"
"pipx:ansible" = "latest"
"pipx:ansible-lint" = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
shfmt = "latest"
ttyd = "latest"
usage = "latest"
vhs = "latest"
vivid = "latest"
"npm:@devcontainers/cli" = "latest"
coder = "2.15.0"
"npm:dclint" = "latest"
"npm:renovate" = "latest"
"npm:jsonlint" = "1.6.3"
"npm:aws-cdk" = "2.1002.0"
taplo = "0.9.3"

[settings]
experimental = true
