[tools]
act = "0.2.81"
air = "1.62.0"
"aqua:8051Enthusiast/biodiff" = "1.2.1"
"aqua:JanDeDobbeleer/oh-my-posh" = "26.22.2"
"aqua:firecow/gitlab-ci-local" = "4.61.1"
"aqua:quarylabs/sqruff" = "0.29.3"
"aqua:rhysd/vim-startuptime" = "1.3.2"
"aqua:rossmacarthur/sheldon" = "0.8.5"
"aqua:sharkdp/hexyl" = "0.16.0"
"aqua:sheepla/pingu" = "0.0.5"
bat = "0.25.0"
delta = "0.18.2"
dust = "1.2.1"
fd = "10.2.0"
fzf = "0.62.0"
gh = "2.74.1"
ghq = "1.8.0"
go = "1.25.1"
"go:github.com/fatih/gomodifytags" = "v1.17.0"
"go:github.com/nametake/golangci-lint-langserver" = "0.0.11"
"go:golang.org/x/tools/cmd/godoc" = "v0.36.0"
"go:golang.org/x/tools/cmd/goimports" = "0.37.0"
"go:golang.org/x/tools/gopls" = "0.20.0"
golangci-lint = "2.4.0"
gotestsum = "1.12.3"
hyperfine = "1.19.0"
lua-language-server = "3.14.0"
neovim = "0.11.3"
node = "24.4.1"
"npm:@biomejs/biome" = "1.9.4"
"npm:@devcontainers/cli" = "0.80.1"
"npm:aicommit2" = "2.2.24"
"npm:bash-language-server" = "5.6.0"
"npm:czg" = "1.12.0"
"npm:dockerfile-language-server-nodejs" = "0.14.0"
"npm:http-server" = "14.1.1"
"npm:jsonlint" = "1.6.3"
"npm:typescript-language-server" = "4.3.4"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:wscat" = "6.1.0"
"npm:yaml-language-server" = "1.18.0"
oauth2c = "latest"
pipx = "1.7.1"
python = "3.13.4"
ripgrep = "14.1.1"
shellcheck = "0.11.0"
shfmt = "3.12.0"
stylua = "2.1.0"
taplo = { version = "0.10.0", matching = "full" }
usage = "2.2.2"
vhs = "0.9.0"
vivid = "0.10.1"
websocat = "1.14.0"
yq = "4.47.2"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
