[tools]
act = "0.2.78"
air = "1.62.0"
"aqua:8051Enthusiast/biodiff" = "1.2.1"
"aqua:JanDeDobbeleer/oh-my-posh" = "26.13.0"
"aqua:firecow/gitlab-ci-local" = "4.61.0"
"aqua:quarylabs/sqruff" = "0.27.0"
"aqua:rhysd/vim-startuptime" = "1.3.2"
"aqua:rossmacarthur/sheldon" = "0.8.2"
"aqua:sharkdp/hexyl" = "0.16.0"
"aqua:sheepla/pingu" = "0.0.5"
awscli = "2.27.46"
bat = "0.25.0"
coder = "2.23.1"
delta = "0.18.2"
dust = "1.2.1"
fd = "10.2.0"
fzf = "0.62.0"
gh = "2.74.1"
ghq = "1.8.0"
go = "1.24.4"
"go:github.com/nametake/golangci-lint-langserver" = "0.0.11"
"go:golang.org/x/tools/cmd/goimports" = "0.34.0"
"go:golang.org/x/tools/gopls" = "0.19.1"
golangci-lint = "2.2.1"
gotestsum = "1.12.2"
hyperfine = "1.19.0"
kompose = "1.36.0"
kube-linter = "0.7.2"
lua-language-server = "3.14.0"
neovim = "0.11.2"
nfpm = "2.43.0"
node = "24.3.0"
"npm:@biomejs/biome" = "1.9.4"
"npm:@devcontainers/cli" = "0.78.0"
"npm:aicommit2" = "2.2.22"
"npm:aws-cdk" = "2.1019.2"
"npm:bash-language-server" = "5.6.0"
"npm:czg" = "1.11.2"
"npm:dclint" = "2.2.2"
"npm:devcontainer" = "0.3.0"
"npm:dockerfile-language-server-nodejs" = "0.14.0"
"npm:http-server" = "14.1.1"
"npm:jsonlint" = "1.6.3"
"npm:tabby-agent" = "1.8.0"
"npm:typescript-language-server" = "4.3.4"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:wscat" = "6.1.0"
"npm:yaml-language-server" = "1.18.0"
pipx = "1.7.1"
"pipx:ansible" = "11.7.0"
"pipx:ansible-lint" = "25.6.1"
python = "3.13.4"
ripgrep = "14.1.1"
rust = "1.88.0"
shellcheck = "0.10.0"
shfmt = "3.11.0"
stylua = "2.1.0"
taplo = { version = "0.10.0", matching = "full" }
ttyd = "1.7.7"
usage = "2.1.1"
vhs = "0.9.0"
vivid = "0.10.1"
websocat = "1.14.0"
yq = "4.45.4"

[settings]
experimental = true
