[tools]
neovim = "0.10.1"
go = "latest"
"npm:devcontainer" = "latest"
node = "20"
"npm:aicommit2" = "latest"
rust = "latest"
python = "latest"
"cargo:pay-respects" = "latest"
vhs = "latest"
ttyd = "latest"
