[tools]
act = "0.2.78"
air = "latest"
"aqua:8051Enthusiast/biodiff" = "latest"
"aqua:JanDeDobbeleer/oh-my-posh" = "latest"
"aqua:firecow/gitlab-ci-local" = "4.60.1"
"aqua:rhysd/vim-startuptime" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
"aqua:sharkdp/hexyl" = "latest"
"aqua:sheepla/pingu" = "latest"
awscli = "latest"
bat = "latest"
"cargo:pay-respects" = "latest"
coder = "2.15.0"
delta = "latest"
dust = "1.1.1"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
go = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "0.0.11"
"go:golang.org/x/tools/cmd/goimports" = "0.33.0"
"go:golang.org/x/tools/gopls" = "0.18.1"
golangci-lint = "latest"
hyperfine = "1.19.0"
lua-language-server = "latest"
neovim = "0.11"
nfpm = "latest"
node = "22.16.0"
"npm:@biomejs/biome" = "1.9.4"
"npm:@devcontainers/cli" = "latest"
"npm:aicommit2" = "latest"
"npm:aws-cdk" = "2.1017.1"
"npm:bash-language-server" = "5.6.0"
"npm:czg" = "latest"
"npm:dclint" = "latest"
"npm:devcontainer" = "latest"
"npm:dockerfile-language-server-nodejs" = "0.14.0"
"npm:http-server" = "latest"
"npm:jsonlint" = "1.6.3"
"npm:renovate" = "latest"
"npm:tabby-agent" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "4.3.4"
"npm:vscode-langservers-extracted" = "4.10.0"
"npm:yaml-language-server" = "1.18.0"
"pipx:ansible" = "latest"
"pipx:ansible-lint" = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "0.10.0"
shfmt = "3.11.0"
stylua = "2.0.2"
taplo = "0.9.3"
ttyd = "latest"
usage = "latest"
vhs = "latest"
vivid = "latest"
yq = "latest"

[settings]
experimental = true
